src/car/urls.py
from django.urls import path
from . import views
from .viewset import getJson

urlpatterns = [
    path('cars', views.ListCreateCarView.as_view()),
    path(r'api/data/', getJson, name='getJson'),
    path('cars/<int:pk>', views.UpdateDeleteCarView.as_view()),
]

src/mydjango/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


# from myapp.views import ShowHelloWorld, index_view, IndexView, tester, viewlist

from user import views as UserViews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('core.urls')),
    url('', include('car.urls')),
    # url('', include('course.urls')),
    url('user/', include('learn.urls')),
    # url(r'^$', UserViews.indexHome),
    # path('home/', index_view, name='home'),
    # path("myapp/", include("myapp.urls")),
    # path('demo/', IndexView.as_view(), name='abc' ),
    # path('demo-new/', IndexView.as_view(), name='abc' ),
    # path('demo-new-2/', IndexView.as_view(), name='abc' ),
    # path('demo-new-4/', IndexView.as_view(), name='abc' ),
    # path('demo-new-5/', IndexView.as_view(), name='abc' ),
    # path("news/", include("news.urls")),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    # path('index_view/', views.index_view, name='index_view'),
    # path('index_view-2/', views.index_view, name='index_view'),
    # path('tester/', tester ),
    # path('list/', viewlist, name='view_list' ),
    # path('detail/<int:question_id>', views.detailView, name='detail' ),
    # path('<int:question_id>', views.vote, name='vote' ),
    path('', views.IndexClass.as_view(), name='index' ),
    path('save/', views.ClassSaveNews.as_view(), name='save' ),
    path('email/', views.email_view, name='email' ),
    path('process/', views.process, name='process' ),

]

src/news/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

# class Post(models.Model):
#     title = models.CharField(max_length=255, blank=False, null=False) # bank=False không được rỗng, null=False (không được null)
#     content = models.TextField(max_length=1000, blank=False, null=False)
#     time_create = models.DateTimeField(default=timezone.datetime.now())
#     # django.utils.timezone.now

#     def __str__(self): # cấu hình trong /admin
#         return self.title # hiển thị title ra thay vì Object

src/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .form import PostForm, SendEmail
from django.views import View

# Create your views here.

class IndexClass(View): # kế thừa từ View
    def get(self, request):
        return HttpResponse('news index')

class ClassSaveNews(View):
    def get(self, request):
        a = PostForm()
        context = { 'f': a }
        return render(request, 'news/add_news.html', context)

    def post(self, request):
        g = PostForm(request.POST)
        if g.is_valid():
            g.save()
            return HttpResponse('luu ok')
        else:
            return HttpResponse('khong duoc validate')
    def put(self):
        pass

    def patch(self):
        pass

def email_view(request):
    b = SendEmail()
    return render(request, 'news/email.html', { 'f': b })

def process(request):
    if request.method == 'POST':
        m = SendEmail(request.POST) 
        if m.is_valid():
            tieude = m.cleaned_data['title']
            cc = m.cleaned_data['cc'] # cc có nghĩa là có gửi 1 bản đính kèm cho người khác hay không
            noidung = m.cleaned_data['content']
            email = m.cleaned_data['email']

            context = { # có thể gửi cả m sang
                'td': tieude, 
                'c': cc,
                'b': noidung,
                'd': email
            }
            
            return render(request, 'news/print_email.html', context)
        
        else:
            return HttpResponse('khong duoc validate')
    else:
        return HttpResponse('send mail fail')

src/news/templates/news/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'news:save' %}" method="post">
        {% csrf_token %}
        <p>
            {{ f.title }}
        </p>
        <p>
            {{ f.content }}
        </p>
        <p>
            {{ f.time_create }}
        </p>
        <input type="submit" value='Thêm'>
    </form>
</body>
</html>

src/news/templates/news/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .classContent {
            padding: 40px;
        }
    </style>
</head>
<body>
    <form action="{% url 'news:process' %}" method='post'>
        {% csrf_token %}
        {{ f }}
        <input type="submit" value='Gửi mail'>
    </form> 
</body>
</html>

src/news/templates/news/print_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        td {
            border: 1px solid #000;
        }
    </style>
</head>
<body>
    <table>
        <tr>
            <td>Tiêu đề</td>
            <td>Nội dung</td>
            <td>Email</td>
            <td>CC</td>
        </tr>
        <tr>
            <td>{{ td }}</td>
            <td>{{ b }}</td>
            <td>{{ d }}</td>
            <td>{{ c }}</td>
        </tr>
    </table>
</body>
</html>