src/car/urls.py
from django.urls import path
from . import views
from .viewset import getJson

urlpatterns = [
    path('cars', views.ListCreateCarView.as_view()),
    path(r'api/data/', getJson, name='getJson'),
    path('cars/<int:pk>', views.UpdateDeleteCarView.as_view()),
]

src/myapp/urls.py
from django.urls import path
from . import views
from myapp.views import ShowHelloWorld, index_view, IndexView, tester, viewlist, detailView
from myapp import views 

app_name = 'myapp'
urlpatterns = [
    path('index_view/', views.index_view, name='index_view'),
    path('index_view-2/', views.index_view, name='index_view'),
    path('tester/', tester ),
    path('list/', viewlist, name='view_list' ),
    path('detail/<int:question_id>', views.detailView, name='detail' ),
    path('<int:question_id>', views.vote, name='vote' ),
]

src/mydjango/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


# from myapp.views import ShowHelloWorld, index_view, IndexView, tester, viewlist

from user import views as UserViews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('core.urls')),
    url('', include('car.urls')),
    # url('', include('course.urls')),
    url('user/', include('learn.urls')),
    # url(r'^$', UserViews.indexHome),
    # path('home/', index_view, name='home'),
    # path("myapp/", include("myapp.urls")),
    # path('demo/', IndexView.as_view(), name='abc' ),
    # path('demo-new/', IndexView.as_view(), name='abc' ),
    # path('demo-new-2/', IndexView.as_view(), name='abc' ),
    # path('demo-new-4/', IndexView.as_view(), name='abc' ),
    # path('demo-new-5/', IndexView.as_view(), name='abc' ),
    # path("news/", include("news.urls")),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/myapp/models.py
from django.db import models


class DemoModel(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    image = models.ImageField(upload_to="demo_images")

    def __str__(self):
        return self.title

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    time_pub = models.DateTimeField()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # CASCADE câu hỏi bị xóa câu trả lời củng bị xóa
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)

src/myapp/forms.py
from django import forms
from .models import ItemBatch


class SomeForm(forms.ModelForm):
    class Meta:
        model = ItemBatch
        fields = '__all__'

    def save(self, commit=True):
        image = self.cleaned_data.pop('image')
        instance = super().save(commit=True)
        # instance.save_m2m()
        print(image)
        instance.image = image
        instance.save()
        return instance

src/myapp/views.py
from django.views.generic import TemplateView
from .tasks import show_hello_world
from .models import DemoModel
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render, get_list_or_404
# Create your views here.
from .models import Question


class ShowHelloWorld(TemplateView):
    template_name = 'hello_world.html'

    def get(self, *args, **kwargs):
        show_hello_world.apply()
        return super().get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['demo_content'] = DemoModel.objects.all()
        return context

def index_view(request):
    return HttpResponse('xin chao')

class IndexView(View):
    def get(self, request): # class nên cần phải có self
        return HttpResponse('ham get')

    def post(self, request):
        return HttpResponse('ham post')

def tester(request):
    taiSan = ['maytinh', 'dien thoai', 'test_1', 'test_2']
    context = {
        'name' : 'test_name',
        'taiSan': taiSan
    }
    return render(request, 'myapp/index.html', context)

def viewlist(request):
    # list_question = get_list_or_404(Question, pk=1) # pk=2 tìm khóa chính(id) = 2
    # list_question = get_list_or_404(Question, question_text='Bạn bao nhiêu tuỏi')
    list_question = Question.objects.all()
    context = {"data": list_question}
    return render(request, 'myapp/question_list.html', context)

def detailView(request, question_id):
    q = Question.objects.get(pk=question_id)
    # q = get_list_or_404(Question, pk=question_id)
    context = {
        'qs': q
    }
    return render(request, 'myapp/detail_question.html', context)

def vote(request, question_id):
    q = Question.objects.get(pk=question_id)
    try:
        dulieu = request.POST['choice']
        c = q.choice_set.get(pk=dulieu)
        c.vote = c.vote + 1
    except:
        return HttpResponse('Lỗi không có choice')

    c.save()

    context = { 'q': q }
    return render(request, 'myapp/result.html', context)

src/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title></title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'myapp/style.css' %}" />
    </head>
    <body>
        <div class="header">
            <h1>My website</h1>
        </div>
        <div class="menu">
            <ul>
                <li>link 1</li>
                <li>link 2</li>
                <li>link 3</li>
                <li>link 4</li>
            </ul>
        </div>

        <div class="noidung">
            {% block content_1 %}

            {% endblock %}
        </div>
        <script src="" async defer></script>
    </body>
</html>

src/myapp/templates/myapp/detail_question.html
{% extends 'myapp/base.html' %}

{% block content_1 %}
    {% if qs %}
        <h1>{{ qs.question_text }}</h1>
        <form action="{% url 'myapp:vote' qs.id %}" method='post'>
            {% csrf_token %}
            <ul>
                {% for item in qs.choice_set.all %}
                    <li>
                        <input type="radio" value="{{ item.id }}" name="choice" /> {{ item.choice_text }}
                    </li>
                {% endfor %}
                <p>
                    <input type="submit" value="gửi" />
                </p>
            </ul>
        </form>
    {% else %}
        <h3>Câu hỏi này không tồn tại</h3>
    {% endif %}
{% endblock %}

src/myapp/templates/myapp/index.html
    
    {% extends 'myapp/base.html' %}
    
    {% block content_1  %}
        <div class="">Đây là template <b>{{name}}</b></div>
        <p class="">Test</p>
        <h1>Asset</h1>
        <ul>
            {% for item in taiSan %}
                {% if item != 'test_1' %}
                    <li>{{item}}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endblock  %}

src/myapp/templates/myapp/question_list.html
{% extends 'myapp/base.html' %}

{% block content_1 %}
    {% if data %}
    {% for item in data %}
        <a href="{% url 'myapp:detail' item.id %}">
            <p>{{ item.question_text }}</p>
        </a>
    {% endfor %}
    {% endif %}
{% endblock %}

src/myapp/templates/myapp/result.html
{% extends 'myapp/base.html' %}

{% block content_1 %}
    {% if q %}
        <h1>
            {{ q.question_text }}
        </h1>
        <p>Kết quả của cuộc bình chọn là:</p>
        {% for item in q.choice_set.all  %}
            <p>{{item.choice_text}} : vote = {{ item.vote }}</p>
        {% endfor %}
        <a href="{% url 'myapp:view_list' %}">Vote tiếp</a>
    {% endif %}
{% endblock %}